package com.resumebucket.resumes.constant;

public enum ResumeStateChangedEventEventType {
	RESUME_ADDED, 
	RESUME_CONTACT_UPDATED, 
	RESUME_SUMMARY_UPDATED,
	RESUME_EXPERIENCES_UPDATED,
	RESUME_EDUCATIONS_UPDATED,
	RESUME_CERTIFICATES_UPDATED,
	RESUME_SKILLS_UPDATED,
	RESUME_AWARDS_UPDATED,
	RESUME_LANGUAGES_UPDATED,
	RESUME_INTERESTS_UPDATED,
	RESUME_DELETED;
}